// Builds and prints a payment receipt. It prints from a hidden frame with its own plain styles,
// so the result is the same black-on-white page whatever theme or screen size the app is using.

export const COMPANY_NAME = 'Jubal Brothers Cable TV Corp'
export const COMPANY_BRANCH = 'Palayan Branch'

const esc = (value) =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

export const pesoText = (value) =>
  `₱${Number(value || 0).toLocaleString('en-PH', { minimumFractionDigits: 2 })}`

export const receiptDate = (value) =>
  value
    ? new Date(value).toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' })
    : '—'

/** Rows shown on the receipt, in order. Shared by the on-screen preview and the printout. */
export function receiptRows({ payment, subscriber }) {
  const rows = [
    ['Received from', subscriber?.name],
    ['Address', subscriber?.address],
    ['Contact number', subscriber?.contact_number],
    ['Service plan', subscriber?.plan_name],
    ['Payment date', receiptDate(payment.payment_date)],
    ['Payment method', payment.payment_method],
    ['Notes', payment.notes],
    ['Received by', payment.received_by],
  ]
  return rows.filter(([, value]) => value)
}

export function printReceipt(data) {
  const { payment } = data
  const rows = receiptRows(data)
    .map(([label, value]) => `<tr><th>${esc(label)}</th><td>${esc(value)}</td></tr>`)
    .join('')

  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Receipt ${esc(payment.or_number)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; color: #111; margin: 0; padding: 32px; }
  .receipt { max-width: 560px; margin: 0 auto; border: 1px solid #444; padding: 28px; }
  h1 { font-size: 18px; margin: 0; text-align: center; }
  .branch { text-align: center; font-size: 13px; color: #444; margin: 2px 0 14px; }
  h2 { font-size: 14px; letter-spacing: 2px; text-align: center; margin: 0 0 18px; padding: 6px 0; border-top: 1px solid #444; border-bottom: 1px solid #444; }
  .no { display: flex; justify-content: space-between; font-size: 13px; margin-bottom: 14px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; font-weight: normal; color: #555; padding: 6px 12px 6px 0; width: 38%; vertical-align: top; }
  td { padding: 6px 0; vertical-align: top; }
  .amount { margin: 18px 0; padding: 12px; border: 2px solid #111; text-align: center; }
  .amount small { display: block; font-size: 11px; color: #555; letter-spacing: 1px; text-transform: uppercase; }
  .amount strong { font-size: 26px; }
  .foot { margin-top: 22px; font-size: 11px; color: #555; text-align: center; }
  @page { margin: 12mm; }
</style></head>
<body><div class="receipt">
  <h1>${esc(COMPANY_NAME)}</h1>
  <div class="branch">${esc(COMPANY_BRANCH)}</div>
  <h2>PAYMENT RECEIPT</h2>
  <div class="no"><span>Receipt / OR No.: <strong>${esc(payment.or_number)}</strong></span></div>
  <div class="amount"><small>Amount received</small><strong>${esc(pesoText(payment.amount))}</strong></div>
  <table>${rows}</table>
  <div class="foot">Thank you for your payment. Printed ${esc(receiptDate(new Date()))}.<br>This receipt was generated by SWIFT from the recorded payment.</div>
</div></body></html>`

  const frame = document.createElement('iframe')
  frame.setAttribute('aria-hidden', 'true')
  frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;'
  document.body.appendChild(frame)

  const cleanup = () => setTimeout(() => frame.remove(), 1000)
  frame.onload = () => {
    const win = frame.contentWindow
    win.onafterprint = cleanup
    win.focus()
    win.print()
    // Some browsers never fire afterprint; don't leave the frame behind forever.
    setTimeout(() => frame.remove(), 60000)
  }
  frame.srcdoc = html
}
